on:
  push:
    branches:
      - "gh-deploy" # change to the branch you wish to deploy from

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.0
    - name: Install deps
      run: npm i && npm ci
    - name: Build
      run: npm run build
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
      with:
        path: packages/docs/storybook-static # change to your build folder